import { TokenType } from "@supernovaio/sdk-exporters"

export const DEFAULT_STYLE_FILE_NAMES: Record<TokenType, string> = {
  Color: "color.scss",
  Typography: "typography.scss",
  Dimension: "dimension.scss",
  Size: "size.scss",
  Space: "space.scss",
  Opacity: "opacity.scss",
  FontSize: "font-size.scss",
  LineHeight: "line-height.scss",
  LetterSpacing: "letter-spacing.scss",
  ParagraphSpacing: "paragraph-spacing.scss",
  BorderWidth: "border-width.scss",
  BorderRadius: "border-radius.scss",
  Duration: "duration.scss",
  ZIndex: "z-index.scss",
  Shadow: "shadow.scss",
  Border: "border.scss",
  Gradient: "gradient.scss",
  String: "string.scss",
  ProductCopy: "product-copy.scss",
  FontFamily: "font-family.scss",
  FontWeight: "font-weight.scss",
  TextCase: "text-case.scss",
  TextDecoration: "text-decoration.scss",
  Visibility: "visibility.scss",
  Blur: "blur.scss"
}

export const DEFAULT_TOKEN_PREFIXES: Record<TokenType, string> = {
  Color: "",
  Typography: "",
  Dimension: "",
  Size: "",
  Space: "",
  Opacity: "",
  FontSize: "",
  LineHeight: "",
  LetterSpacing: "",
  ParagraphSpacing: "",
  BorderWidth: "",
  BorderRadius: "",
  Duration: "",
  ZIndex: "",
  Shadow: "",
  Border: "",
  Gradient: "",
  String: "",
  ProductCopy: "",
  FontFamily: "",
  FontWeight: "",
  TextCase: "",
  TextDecoration: "",
  Visibility: "",
  Blur: ""
} 